// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/TextPrimitive.proto

#include "foxglove/TextPrimitive.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_foxglove_2fColor_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fColor_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Color;
}  // namespace protobuf_foxglove_2fColor_2eproto
namespace protobuf_foxglove_2fPose_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fPose_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_Pose;
}  // namespace protobuf_foxglove_2fPose_2eproto
namespace foxglove {
class TextPrimitiveDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TextPrimitive>
      _instance;
} _TextPrimitive_default_instance_;
}  // namespace foxglove
namespace protobuf_foxglove_2fTextPrimitive_2eproto {
static void InitDefaultsTextPrimitive() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::foxglove::_TextPrimitive_default_instance_;
    new (ptr) ::foxglove::TextPrimitive();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::foxglove::TextPrimitive::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_TextPrimitive =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsTextPrimitive}, {
      &protobuf_foxglove_2fPose_2eproto::scc_info_Pose.base,
      &protobuf_foxglove_2fColor_2eproto::scc_info_Color.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_TextPrimitive.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextPrimitive, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextPrimitive, pose_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextPrimitive, billboard_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextPrimitive, font_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextPrimitive, scale_invariant_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextPrimitive, color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextPrimitive, text_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::foxglove::TextPrimitive)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::foxglove::_TextPrimitive_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "foxglove/TextPrimitive.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\034foxglove/TextPrimitive.proto\022\010foxglove"
      "\032\024foxglove/Color.proto\032\023foxglove/Pose.pr"
      "oto\"\232\001\n\rTextPrimitive\022\034\n\004pose\030\001 \001(\0132\016.fo"
      "xglove.Pose\022\021\n\tbillboard\030\002 \001(\010\022\021\n\tfont_s"
      "ize\030\003 \001(\001\022\027\n\017scale_invariant\030\004 \001(\010\022\036\n\005co"
      "lor\030\005 \001(\0132\017.foxglove.Color\022\014\n\004text\030\006 \001(\t"
      "b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 248);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "foxglove/TextPrimitive.proto", &protobuf_RegisterTypes);
  ::protobuf_foxglove_2fColor_2eproto::AddDescriptors();
  ::protobuf_foxglove_2fPose_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_foxglove_2fTextPrimitive_2eproto
namespace foxglove {

// ===================================================================

void TextPrimitive::InitAsDefaultInstance() {
  ::foxglove::_TextPrimitive_default_instance_._instance.get_mutable()->pose_ = const_cast< ::foxglove::Pose*>(
      ::foxglove::Pose::internal_default_instance());
  ::foxglove::_TextPrimitive_default_instance_._instance.get_mutable()->color_ = const_cast< ::foxglove::Color*>(
      ::foxglove::Color::internal_default_instance());
}
void TextPrimitive::clear_pose() {
  if (GetArenaNoVirtual() == NULL && pose_ != NULL) {
    delete pose_;
  }
  pose_ = NULL;
}
void TextPrimitive::clear_color() {
  if (GetArenaNoVirtual() == NULL && color_ != NULL) {
    delete color_;
  }
  color_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TextPrimitive::kPoseFieldNumber;
const int TextPrimitive::kBillboardFieldNumber;
const int TextPrimitive::kFontSizeFieldNumber;
const int TextPrimitive::kScaleInvariantFieldNumber;
const int TextPrimitive::kColorFieldNumber;
const int TextPrimitive::kTextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TextPrimitive::TextPrimitive()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_foxglove_2fTextPrimitive_2eproto::scc_info_TextPrimitive.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:foxglove.TextPrimitive)
}
TextPrimitive::TextPrimitive(const TextPrimitive& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.text().size() > 0) {
    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  if (from.has_pose()) {
    pose_ = new ::foxglove::Pose(*from.pose_);
  } else {
    pose_ = NULL;
  }
  if (from.has_color()) {
    color_ = new ::foxglove::Color(*from.color_);
  } else {
    color_ = NULL;
  }
  ::memcpy(&font_size_, &from.font_size_,
    static_cast<size_t>(reinterpret_cast<char*>(&scale_invariant_) -
    reinterpret_cast<char*>(&font_size_)) + sizeof(scale_invariant_));
  // @@protoc_insertion_point(copy_constructor:foxglove.TextPrimitive)
}

void TextPrimitive::SharedCtor() {
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&pose_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&scale_invariant_) -
      reinterpret_cast<char*>(&pose_)) + sizeof(scale_invariant_));
}

TextPrimitive::~TextPrimitive() {
  // @@protoc_insertion_point(destructor:foxglove.TextPrimitive)
  SharedDtor();
}

void TextPrimitive::SharedDtor() {
  text_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete pose_;
  if (this != internal_default_instance()) delete color_;
}

void TextPrimitive::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* TextPrimitive::descriptor() {
  ::protobuf_foxglove_2fTextPrimitive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_foxglove_2fTextPrimitive_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TextPrimitive& TextPrimitive::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_foxglove_2fTextPrimitive_2eproto::scc_info_TextPrimitive.base);
  return *internal_default_instance();
}


void TextPrimitive::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.TextPrimitive)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && pose_ != NULL) {
    delete pose_;
  }
  pose_ = NULL;
  if (GetArenaNoVirtual() == NULL && color_ != NULL) {
    delete color_;
  }
  color_ = NULL;
  ::memset(&font_size_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&scale_invariant_) -
      reinterpret_cast<char*>(&font_size_)) + sizeof(scale_invariant_));
  _internal_metadata_.Clear();
}

bool TextPrimitive::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:foxglove.TextPrimitive)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .foxglove.Pose pose = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_pose()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool billboard = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &billboard_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double font_size = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &font_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool scale_invariant = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &scale_invariant_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .foxglove.Color color = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string text = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->text().data(), static_cast<int>(this->text().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "foxglove.TextPrimitive.text"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:foxglove.TextPrimitive)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:foxglove.TextPrimitive)
  return false;
#undef DO_
}

void TextPrimitive::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:foxglove.TextPrimitive)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .foxglove.Pose pose = 1;
  if (this->has_pose()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_pose(), output);
  }

  // bool billboard = 2;
  if (this->billboard() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->billboard(), output);
  }

  // double font_size = 3;
  if (this->font_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->font_size(), output);
  }

  // bool scale_invariant = 4;
  if (this->scale_invariant() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->scale_invariant(), output);
  }

  // .foxglove.Color color = 5;
  if (this->has_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_color(), output);
  }

  // string text = 6;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foxglove.TextPrimitive.text");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->text(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:foxglove.TextPrimitive)
}

::google::protobuf::uint8* TextPrimitive::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.TextPrimitive)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .foxglove.Pose pose = 1;
  if (this->has_pose()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_pose(), deterministic, target);
  }

  // bool billboard = 2;
  if (this->billboard() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->billboard(), target);
  }

  // double font_size = 3;
  if (this->font_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->font_size(), target);
  }

  // bool scale_invariant = 4;
  if (this->scale_invariant() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->scale_invariant(), target);
  }

  // .foxglove.Color color = 5;
  if (this->has_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_color(), deterministic, target);
  }

  // string text = 6;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foxglove.TextPrimitive.text");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->text(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.TextPrimitive)
  return target;
}

size_t TextPrimitive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.TextPrimitive)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string text = 6;
  if (this->text().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->text());
  }

  // .foxglove.Pose pose = 1;
  if (this->has_pose()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *pose_);
  }

  // .foxglove.Color color = 5;
  if (this->has_color()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *color_);
  }

  // double font_size = 3;
  if (this->font_size() != 0) {
    total_size += 1 + 8;
  }

  // bool billboard = 2;
  if (this->billboard() != 0) {
    total_size += 1 + 1;
  }

  // bool scale_invariant = 4;
  if (this->scale_invariant() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TextPrimitive::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:foxglove.TextPrimitive)
  GOOGLE_DCHECK_NE(&from, this);
  const TextPrimitive* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TextPrimitive>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:foxglove.TextPrimitive)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:foxglove.TextPrimitive)
    MergeFrom(*source);
  }
}

void TextPrimitive::MergeFrom(const TextPrimitive& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:foxglove.TextPrimitive)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.text().size() > 0) {

    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  if (from.has_pose()) {
    mutable_pose()->::foxglove::Pose::MergeFrom(from.pose());
  }
  if (from.has_color()) {
    mutable_color()->::foxglove::Color::MergeFrom(from.color());
  }
  if (from.font_size() != 0) {
    set_font_size(from.font_size());
  }
  if (from.billboard() != 0) {
    set_billboard(from.billboard());
  }
  if (from.scale_invariant() != 0) {
    set_scale_invariant(from.scale_invariant());
  }
}

void TextPrimitive::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:foxglove.TextPrimitive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TextPrimitive::CopyFrom(const TextPrimitive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.TextPrimitive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TextPrimitive::IsInitialized() const {
  return true;
}

void TextPrimitive::Swap(TextPrimitive* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TextPrimitive::InternalSwap(TextPrimitive* other) {
  using std::swap;
  text_.Swap(&other->text_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(pose_, other->pose_);
  swap(color_, other->color_);
  swap(font_size_, other->font_size_);
  swap(billboard_, other->billboard_);
  swap(scale_invariant_, other->scale_invariant_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata TextPrimitive::GetMetadata() const {
  protobuf_foxglove_2fTextPrimitive_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_foxglove_2fTextPrimitive_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::foxglove::TextPrimitive* Arena::CreateMaybeMessage< ::foxglove::TextPrimitive >(Arena* arena) {
  return Arena::CreateInternal< ::foxglove::TextPrimitive >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
