// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/TextAnnotation.proto

#include "foxglove/TextAnnotation.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_foxglove_2fColor_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fColor_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Color;
}  // namespace protobuf_foxglove_2fColor_2eproto
namespace protobuf_foxglove_2fPoint2_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fPoint2_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Point2;
}  // namespace protobuf_foxglove_2fPoint2_2eproto
namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2ftimestamp_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Timestamp;
}  // namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto
namespace foxglove {
class TextAnnotationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TextAnnotation>
      _instance;
} _TextAnnotation_default_instance_;
}  // namespace foxglove
namespace protobuf_foxglove_2fTextAnnotation_2eproto {
static void InitDefaultsTextAnnotation() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::foxglove::_TextAnnotation_default_instance_;
    new (ptr) ::foxglove::TextAnnotation();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::foxglove::TextAnnotation::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_TextAnnotation =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsTextAnnotation}, {
      &protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp.base,
      &protobuf_foxglove_2fPoint2_2eproto::scc_info_Point2.base,
      &protobuf_foxglove_2fColor_2eproto::scc_info_Color.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_TextAnnotation.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextAnnotation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextAnnotation, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextAnnotation, position_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextAnnotation, text_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextAnnotation, font_size_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextAnnotation, text_color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::foxglove::TextAnnotation, background_color_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::foxglove::TextAnnotation)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::foxglove::_TextAnnotation_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "foxglove/TextAnnotation.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035foxglove/TextAnnotation.proto\022\010foxglov"
      "e\032\024foxglove/Color.proto\032\025foxglove/Point2"
      ".proto\032\037google/protobuf/timestamp.proto\""
      "\324\001\n\016TextAnnotation\022-\n\ttimestamp\030\001 \001(\0132\032."
      "google.protobuf.Timestamp\022\"\n\010position\030\002 "
      "\001(\0132\020.foxglove.Point2\022\014\n\004text\030\003 \001(\t\022\021\n\tf"
      "ont_size\030\004 \001(\001\022#\n\ntext_color\030\005 \001(\0132\017.fox"
      "glove.Color\022)\n\020background_color\030\006 \001(\0132\017."
      "foxglove.Colorb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 342);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "foxglove/TextAnnotation.proto", &protobuf_RegisterTypes);
  ::protobuf_foxglove_2fColor_2eproto::AddDescriptors();
  ::protobuf_foxglove_2fPoint2_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2ftimestamp_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_foxglove_2fTextAnnotation_2eproto
namespace foxglove {

// ===================================================================

void TextAnnotation::InitAsDefaultInstance() {
  ::foxglove::_TextAnnotation_default_instance_._instance.get_mutable()->timestamp_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
  ::foxglove::_TextAnnotation_default_instance_._instance.get_mutable()->position_ = const_cast< ::foxglove::Point2*>(
      ::foxglove::Point2::internal_default_instance());
  ::foxglove::_TextAnnotation_default_instance_._instance.get_mutable()->text_color_ = const_cast< ::foxglove::Color*>(
      ::foxglove::Color::internal_default_instance());
  ::foxglove::_TextAnnotation_default_instance_._instance.get_mutable()->background_color_ = const_cast< ::foxglove::Color*>(
      ::foxglove::Color::internal_default_instance());
}
void TextAnnotation::clear_timestamp() {
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
}
void TextAnnotation::clear_position() {
  if (GetArenaNoVirtual() == NULL && position_ != NULL) {
    delete position_;
  }
  position_ = NULL;
}
void TextAnnotation::clear_text_color() {
  if (GetArenaNoVirtual() == NULL && text_color_ != NULL) {
    delete text_color_;
  }
  text_color_ = NULL;
}
void TextAnnotation::clear_background_color() {
  if (GetArenaNoVirtual() == NULL && background_color_ != NULL) {
    delete background_color_;
  }
  background_color_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TextAnnotation::kTimestampFieldNumber;
const int TextAnnotation::kPositionFieldNumber;
const int TextAnnotation::kTextFieldNumber;
const int TextAnnotation::kFontSizeFieldNumber;
const int TextAnnotation::kTextColorFieldNumber;
const int TextAnnotation::kBackgroundColorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TextAnnotation::TextAnnotation()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_foxglove_2fTextAnnotation_2eproto::scc_info_TextAnnotation.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:foxglove.TextAnnotation)
}
TextAnnotation::TextAnnotation(const TextAnnotation& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.text().size() > 0) {
    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  if (from.has_timestamp()) {
    timestamp_ = new ::google::protobuf::Timestamp(*from.timestamp_);
  } else {
    timestamp_ = NULL;
  }
  if (from.has_position()) {
    position_ = new ::foxglove::Point2(*from.position_);
  } else {
    position_ = NULL;
  }
  if (from.has_text_color()) {
    text_color_ = new ::foxglove::Color(*from.text_color_);
  } else {
    text_color_ = NULL;
  }
  if (from.has_background_color()) {
    background_color_ = new ::foxglove::Color(*from.background_color_);
  } else {
    background_color_ = NULL;
  }
  font_size_ = from.font_size_;
  // @@protoc_insertion_point(copy_constructor:foxglove.TextAnnotation)
}

void TextAnnotation::SharedCtor() {
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&font_size_) -
      reinterpret_cast<char*>(&timestamp_)) + sizeof(font_size_));
}

TextAnnotation::~TextAnnotation() {
  // @@protoc_insertion_point(destructor:foxglove.TextAnnotation)
  SharedDtor();
}

void TextAnnotation::SharedDtor() {
  text_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete timestamp_;
  if (this != internal_default_instance()) delete position_;
  if (this != internal_default_instance()) delete text_color_;
  if (this != internal_default_instance()) delete background_color_;
}

void TextAnnotation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* TextAnnotation::descriptor() {
  ::protobuf_foxglove_2fTextAnnotation_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_foxglove_2fTextAnnotation_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const TextAnnotation& TextAnnotation::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_foxglove_2fTextAnnotation_2eproto::scc_info_TextAnnotation.base);
  return *internal_default_instance();
}


void TextAnnotation::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.TextAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && timestamp_ != NULL) {
    delete timestamp_;
  }
  timestamp_ = NULL;
  if (GetArenaNoVirtual() == NULL && position_ != NULL) {
    delete position_;
  }
  position_ = NULL;
  if (GetArenaNoVirtual() == NULL && text_color_ != NULL) {
    delete text_color_;
  }
  text_color_ = NULL;
  if (GetArenaNoVirtual() == NULL && background_color_ != NULL) {
    delete background_color_;
  }
  background_color_ = NULL;
  font_size_ = 0;
  _internal_metadata_.Clear();
}

bool TextAnnotation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:foxglove.TextAnnotation)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.protobuf.Timestamp timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_timestamp()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .foxglove.Point2 position = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_position()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string text = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->text().data(), static_cast<int>(this->text().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "foxglove.TextAnnotation.text"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double font_size = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &font_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .foxglove.Color text_color = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_text_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .foxglove.Color background_color = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_background_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:foxglove.TextAnnotation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:foxglove.TextAnnotation)
  return false;
#undef DO_
}

void TextAnnotation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:foxglove.TextAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_timestamp(), output);
  }

  // .foxglove.Point2 position = 2;
  if (this->has_position()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_position(), output);
  }

  // string text = 3;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foxglove.TextAnnotation.text");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->text(), output);
  }

  // double font_size = 4;
  if (this->font_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->font_size(), output);
  }

  // .foxglove.Color text_color = 5;
  if (this->has_text_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->_internal_text_color(), output);
  }

  // .foxglove.Color background_color = 6;
  if (this->has_background_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->_internal_background_color(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:foxglove.TextAnnotation)
}

::google::protobuf::uint8* TextAnnotation::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.TextAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_timestamp(), deterministic, target);
  }

  // .foxglove.Point2 position = 2;
  if (this->has_position()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_position(), deterministic, target);
  }

  // string text = 3;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "foxglove.TextAnnotation.text");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->text(), target);
  }

  // double font_size = 4;
  if (this->font_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->font_size(), target);
  }

  // .foxglove.Color text_color = 5;
  if (this->has_text_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->_internal_text_color(), deterministic, target);
  }

  // .foxglove.Color background_color = 6;
  if (this->has_background_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->_internal_background_color(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.TextAnnotation)
  return target;
}

size_t TextAnnotation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.TextAnnotation)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string text = 3;
  if (this->text().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->text());
  }

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->has_timestamp()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *timestamp_);
  }

  // .foxglove.Point2 position = 2;
  if (this->has_position()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *position_);
  }

  // .foxglove.Color text_color = 5;
  if (this->has_text_color()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *text_color_);
  }

  // .foxglove.Color background_color = 6;
  if (this->has_background_color()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *background_color_);
  }

  // double font_size = 4;
  if (this->font_size() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TextAnnotation::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:foxglove.TextAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  const TextAnnotation* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const TextAnnotation>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:foxglove.TextAnnotation)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:foxglove.TextAnnotation)
    MergeFrom(*source);
  }
}

void TextAnnotation::MergeFrom(const TextAnnotation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:foxglove.TextAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.text().size() > 0) {

    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  if (from.has_timestamp()) {
    mutable_timestamp()->::google::protobuf::Timestamp::MergeFrom(from.timestamp());
  }
  if (from.has_position()) {
    mutable_position()->::foxglove::Point2::MergeFrom(from.position());
  }
  if (from.has_text_color()) {
    mutable_text_color()->::foxglove::Color::MergeFrom(from.text_color());
  }
  if (from.has_background_color()) {
    mutable_background_color()->::foxglove::Color::MergeFrom(from.background_color());
  }
  if (from.font_size() != 0) {
    set_font_size(from.font_size());
  }
}

void TextAnnotation::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:foxglove.TextAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TextAnnotation::CopyFrom(const TextAnnotation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.TextAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TextAnnotation::IsInitialized() const {
  return true;
}

void TextAnnotation::Swap(TextAnnotation* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TextAnnotation::InternalSwap(TextAnnotation* other) {
  using std::swap;
  text_.Swap(&other->text_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(timestamp_, other->timestamp_);
  swap(position_, other->position_);
  swap(text_color_, other->text_color_);
  swap(background_color_, other->background_color_);
  swap(font_size_, other->font_size_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata TextAnnotation::GetMetadata() const {
  protobuf_foxglove_2fTextAnnotation_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_foxglove_2fTextAnnotation_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::foxglove::TextAnnotation* Arena::CreateMaybeMessage< ::foxglove::TextAnnotation >(Arena* arena) {
  return Arena::CreateInternal< ::foxglove::TextAnnotation >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
