// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/ArrowPrimitive.proto

#ifndef PROTOBUF_INCLUDED_foxglove_2fArrowPrimitive_2eproto
#define PROTOBUF_INCLUDED_foxglove_2fArrowPrimitive_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foxglove/Color.pb.h"
#include "foxglove/Pose.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fArrowPrimitive_2eproto 

namespace protobuf_foxglove_2fArrowPrimitive_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_foxglove_2fArrowPrimitive_2eproto
namespace foxglove {
class ArrowPrimitive;
class ArrowPrimitiveDefaultTypeInternal;
extern ArrowPrimitiveDefaultTypeInternal _ArrowPrimitive_default_instance_;
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> ::foxglove::ArrowPrimitive* Arena::CreateMaybeMessage<::foxglove::ArrowPrimitive>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace foxglove {

// ===================================================================

class ArrowPrimitive : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:foxglove.ArrowPrimitive) */ {
 public:
  ArrowPrimitive();
  virtual ~ArrowPrimitive();

  ArrowPrimitive(const ArrowPrimitive& from);

  inline ArrowPrimitive& operator=(const ArrowPrimitive& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArrowPrimitive(ArrowPrimitive&& from) noexcept
    : ArrowPrimitive() {
    *this = ::std::move(from);
  }

  inline ArrowPrimitive& operator=(ArrowPrimitive&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ArrowPrimitive& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArrowPrimitive* internal_default_instance() {
    return reinterpret_cast<const ArrowPrimitive*>(
               &_ArrowPrimitive_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ArrowPrimitive* other);
  friend void swap(ArrowPrimitive& a, ArrowPrimitive& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArrowPrimitive* New() const final {
    return CreateMaybeMessage<ArrowPrimitive>(NULL);
  }

  ArrowPrimitive* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArrowPrimitive>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ArrowPrimitive& from);
  void MergeFrom(const ArrowPrimitive& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ArrowPrimitive* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .foxglove.Pose pose = 1;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 1;
  private:
  const ::foxglove::Pose& _internal_pose() const;
  public:
  const ::foxglove::Pose& pose() const;
  ::foxglove::Pose* release_pose();
  ::foxglove::Pose* mutable_pose();
  void set_allocated_pose(::foxglove::Pose* pose);

  // .foxglove.Color color = 6;
  bool has_color() const;
  void clear_color();
  static const int kColorFieldNumber = 6;
  private:
  const ::foxglove::Color& _internal_color() const;
  public:
  const ::foxglove::Color& color() const;
  ::foxglove::Color* release_color();
  ::foxglove::Color* mutable_color();
  void set_allocated_color(::foxglove::Color* color);

  // double shaft_length = 2;
  void clear_shaft_length();
  static const int kShaftLengthFieldNumber = 2;
  double shaft_length() const;
  void set_shaft_length(double value);

  // double shaft_diameter = 3;
  void clear_shaft_diameter();
  static const int kShaftDiameterFieldNumber = 3;
  double shaft_diameter() const;
  void set_shaft_diameter(double value);

  // double head_length = 4;
  void clear_head_length();
  static const int kHeadLengthFieldNumber = 4;
  double head_length() const;
  void set_head_length(double value);

  // double head_diameter = 5;
  void clear_head_diameter();
  static const int kHeadDiameterFieldNumber = 5;
  double head_diameter() const;
  void set_head_diameter(double value);

  // @@protoc_insertion_point(class_scope:foxglove.ArrowPrimitive)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::foxglove::Pose* pose_;
  ::foxglove::Color* color_;
  double shaft_length_;
  double shaft_diameter_;
  double head_length_;
  double head_diameter_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_foxglove_2fArrowPrimitive_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ArrowPrimitive

// .foxglove.Pose pose = 1;
inline bool ArrowPrimitive::has_pose() const {
  return this != internal_default_instance() && pose_ != NULL;
}
inline const ::foxglove::Pose& ArrowPrimitive::_internal_pose() const {
  return *pose_;
}
inline const ::foxglove::Pose& ArrowPrimitive::pose() const {
  const ::foxglove::Pose* p = pose_;
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.pose)
  return p != NULL ? *p : *reinterpret_cast<const ::foxglove::Pose*>(
      &::foxglove::_Pose_default_instance_);
}
inline ::foxglove::Pose* ArrowPrimitive::release_pose() {
  // @@protoc_insertion_point(field_release:foxglove.ArrowPrimitive.pose)
  
  ::foxglove::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline ::foxglove::Pose* ArrowPrimitive::mutable_pose() {
  
  if (pose_ == NULL) {
    auto* p = CreateMaybeMessage<::foxglove::Pose>(GetArenaNoVirtual());
    pose_ = p;
  }
  // @@protoc_insertion_point(field_mutable:foxglove.ArrowPrimitive.pose)
  return pose_;
}
inline void ArrowPrimitive::set_allocated_pose(::foxglove::Pose* pose) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pose_);
  }
  if (pose) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pose = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pose, submessage_arena);
    }
    
  } else {
    
  }
  pose_ = pose;
  // @@protoc_insertion_point(field_set_allocated:foxglove.ArrowPrimitive.pose)
}

// double shaft_length = 2;
inline void ArrowPrimitive::clear_shaft_length() {
  shaft_length_ = 0;
}
inline double ArrowPrimitive::shaft_length() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.shaft_length)
  return shaft_length_;
}
inline void ArrowPrimitive::set_shaft_length(double value) {
  
  shaft_length_ = value;
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.shaft_length)
}

// double shaft_diameter = 3;
inline void ArrowPrimitive::clear_shaft_diameter() {
  shaft_diameter_ = 0;
}
inline double ArrowPrimitive::shaft_diameter() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.shaft_diameter)
  return shaft_diameter_;
}
inline void ArrowPrimitive::set_shaft_diameter(double value) {
  
  shaft_diameter_ = value;
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.shaft_diameter)
}

// double head_length = 4;
inline void ArrowPrimitive::clear_head_length() {
  head_length_ = 0;
}
inline double ArrowPrimitive::head_length() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.head_length)
  return head_length_;
}
inline void ArrowPrimitive::set_head_length(double value) {
  
  head_length_ = value;
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.head_length)
}

// double head_diameter = 5;
inline void ArrowPrimitive::clear_head_diameter() {
  head_diameter_ = 0;
}
inline double ArrowPrimitive::head_diameter() const {
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.head_diameter)
  return head_diameter_;
}
inline void ArrowPrimitive::set_head_diameter(double value) {
  
  head_diameter_ = value;
  // @@protoc_insertion_point(field_set:foxglove.ArrowPrimitive.head_diameter)
}

// .foxglove.Color color = 6;
inline bool ArrowPrimitive::has_color() const {
  return this != internal_default_instance() && color_ != NULL;
}
inline const ::foxglove::Color& ArrowPrimitive::_internal_color() const {
  return *color_;
}
inline const ::foxglove::Color& ArrowPrimitive::color() const {
  const ::foxglove::Color* p = color_;
  // @@protoc_insertion_point(field_get:foxglove.ArrowPrimitive.color)
  return p != NULL ? *p : *reinterpret_cast<const ::foxglove::Color*>(
      &::foxglove::_Color_default_instance_);
}
inline ::foxglove::Color* ArrowPrimitive::release_color() {
  // @@protoc_insertion_point(field_release:foxglove.ArrowPrimitive.color)
  
  ::foxglove::Color* temp = color_;
  color_ = NULL;
  return temp;
}
inline ::foxglove::Color* ArrowPrimitive::mutable_color() {
  
  if (color_ == NULL) {
    auto* p = CreateMaybeMessage<::foxglove::Color>(GetArenaNoVirtual());
    color_ = p;
  }
  // @@protoc_insertion_point(field_mutable:foxglove.ArrowPrimitive.color)
  return color_;
}
inline void ArrowPrimitive::set_allocated_color(::foxglove::Color* color) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(color_);
  }
  if (color) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      color = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, color, submessage_arena);
    }
    
  } else {
    
  }
  color_ = color;
  // @@protoc_insertion_point(field_set_allocated:foxglove.ArrowPrimitive.color)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_foxglove_2fArrowPrimitive_2eproto
