// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/SceneUpdate.proto

#ifndef PROTOBUF_INCLUDED_foxglove_2fSceneUpdate_2eproto
#define PROTOBUF_INCLUDED_foxglove_2fSceneUpdate_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foxglove/SceneEntity.pb.h"
#include "foxglove/SceneEntityDeletion.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fSceneUpdate_2eproto 

namespace protobuf_foxglove_2fSceneUpdate_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_foxglove_2fSceneUpdate_2eproto
namespace foxglove {
class SceneUpdate;
class SceneUpdateDefaultTypeInternal;
extern SceneUpdateDefaultTypeInternal _SceneUpdate_default_instance_;
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> ::foxglove::SceneUpdate* Arena::CreateMaybeMessage<::foxglove::SceneUpdate>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace foxglove {

// ===================================================================

class SceneUpdate : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:foxglove.SceneUpdate) */ {
 public:
  SceneUpdate();
  virtual ~SceneUpdate();

  SceneUpdate(const SceneUpdate& from);

  inline SceneUpdate& operator=(const SceneUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SceneUpdate(SceneUpdate&& from) noexcept
    : SceneUpdate() {
    *this = ::std::move(from);
  }

  inline SceneUpdate& operator=(SceneUpdate&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SceneUpdate& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SceneUpdate* internal_default_instance() {
    return reinterpret_cast<const SceneUpdate*>(
               &_SceneUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SceneUpdate* other);
  friend void swap(SceneUpdate& a, SceneUpdate& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SceneUpdate* New() const final {
    return CreateMaybeMessage<SceneUpdate>(NULL);
  }

  SceneUpdate* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SceneUpdate>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SceneUpdate& from);
  void MergeFrom(const SceneUpdate& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SceneUpdate* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .foxglove.SceneEntityDeletion deletions = 1;
  int deletions_size() const;
  void clear_deletions();
  static const int kDeletionsFieldNumber = 1;
  ::foxglove::SceneEntityDeletion* mutable_deletions(int index);
  ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntityDeletion >*
      mutable_deletions();
  const ::foxglove::SceneEntityDeletion& deletions(int index) const;
  ::foxglove::SceneEntityDeletion* add_deletions();
  const ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntityDeletion >&
      deletions() const;

  // repeated .foxglove.SceneEntity entities = 2;
  int entities_size() const;
  void clear_entities();
  static const int kEntitiesFieldNumber = 2;
  ::foxglove::SceneEntity* mutable_entities(int index);
  ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntity >*
      mutable_entities();
  const ::foxglove::SceneEntity& entities(int index) const;
  ::foxglove::SceneEntity* add_entities();
  const ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntity >&
      entities() const;

  // @@protoc_insertion_point(class_scope:foxglove.SceneUpdate)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntityDeletion > deletions_;
  ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntity > entities_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_foxglove_2fSceneUpdate_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SceneUpdate

// repeated .foxglove.SceneEntityDeletion deletions = 1;
inline int SceneUpdate::deletions_size() const {
  return deletions_.size();
}
inline ::foxglove::SceneEntityDeletion* SceneUpdate::mutable_deletions(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.SceneUpdate.deletions)
  return deletions_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntityDeletion >*
SceneUpdate::mutable_deletions() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.SceneUpdate.deletions)
  return &deletions_;
}
inline const ::foxglove::SceneEntityDeletion& SceneUpdate::deletions(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.SceneUpdate.deletions)
  return deletions_.Get(index);
}
inline ::foxglove::SceneEntityDeletion* SceneUpdate::add_deletions() {
  // @@protoc_insertion_point(field_add:foxglove.SceneUpdate.deletions)
  return deletions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntityDeletion >&
SceneUpdate::deletions() const {
  // @@protoc_insertion_point(field_list:foxglove.SceneUpdate.deletions)
  return deletions_;
}

// repeated .foxglove.SceneEntity entities = 2;
inline int SceneUpdate::entities_size() const {
  return entities_.size();
}
inline ::foxglove::SceneEntity* SceneUpdate::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.SceneUpdate.entities)
  return entities_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntity >*
SceneUpdate::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.SceneUpdate.entities)
  return &entities_;
}
inline const ::foxglove::SceneEntity& SceneUpdate::entities(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.SceneUpdate.entities)
  return entities_.Get(index);
}
inline ::foxglove::SceneEntity* SceneUpdate::add_entities() {
  // @@protoc_insertion_point(field_add:foxglove.SceneUpdate.entities)
  return entities_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::foxglove::SceneEntity >&
SceneUpdate::entities() const {
  // @@protoc_insertion_point(field_list:foxglove.SceneUpdate.entities)
  return entities_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_foxglove_2fSceneUpdate_2eproto
