// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/SceneEntityDeletion.proto

#ifndef PROTOBUF_INCLUDED_foxglove_2fSceneEntityDeletion_2eproto
#define PROTOBUF_INCLUDED_foxglove_2fSceneEntityDeletion_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_foxglove_2fSceneEntityDeletion_2eproto 

namespace protobuf_foxglove_2fSceneEntityDeletion_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_foxglove_2fSceneEntityDeletion_2eproto
namespace foxglove {
class SceneEntityDeletion;
class SceneEntityDeletionDefaultTypeInternal;
extern SceneEntityDeletionDefaultTypeInternal _SceneEntityDeletion_default_instance_;
}  // namespace foxglove
namespace google {
namespace protobuf {
template<> ::foxglove::SceneEntityDeletion* Arena::CreateMaybeMessage<::foxglove::SceneEntityDeletion>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace foxglove {

enum SceneEntityDeletion_Type {
  SceneEntityDeletion_Type_MATCHING_ID = 0,
  SceneEntityDeletion_Type_ALL = 1,
  SceneEntityDeletion_Type_SceneEntityDeletion_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SceneEntityDeletion_Type_SceneEntityDeletion_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SceneEntityDeletion_Type_IsValid(int value);
const SceneEntityDeletion_Type SceneEntityDeletion_Type_Type_MIN = SceneEntityDeletion_Type_MATCHING_ID;
const SceneEntityDeletion_Type SceneEntityDeletion_Type_Type_MAX = SceneEntityDeletion_Type_ALL;
const int SceneEntityDeletion_Type_Type_ARRAYSIZE = SceneEntityDeletion_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* SceneEntityDeletion_Type_descriptor();
inline const ::std::string& SceneEntityDeletion_Type_Name(SceneEntityDeletion_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    SceneEntityDeletion_Type_descriptor(), value);
}
inline bool SceneEntityDeletion_Type_Parse(
    const ::std::string& name, SceneEntityDeletion_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SceneEntityDeletion_Type>(
    SceneEntityDeletion_Type_descriptor(), name, value);
}
// ===================================================================

class SceneEntityDeletion : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:foxglove.SceneEntityDeletion) */ {
 public:
  SceneEntityDeletion();
  virtual ~SceneEntityDeletion();

  SceneEntityDeletion(const SceneEntityDeletion& from);

  inline SceneEntityDeletion& operator=(const SceneEntityDeletion& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SceneEntityDeletion(SceneEntityDeletion&& from) noexcept
    : SceneEntityDeletion() {
    *this = ::std::move(from);
  }

  inline SceneEntityDeletion& operator=(SceneEntityDeletion&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SceneEntityDeletion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SceneEntityDeletion* internal_default_instance() {
    return reinterpret_cast<const SceneEntityDeletion*>(
               &_SceneEntityDeletion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SceneEntityDeletion* other);
  friend void swap(SceneEntityDeletion& a, SceneEntityDeletion& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SceneEntityDeletion* New() const final {
    return CreateMaybeMessage<SceneEntityDeletion>(NULL);
  }

  SceneEntityDeletion* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SceneEntityDeletion>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SceneEntityDeletion& from);
  void MergeFrom(const SceneEntityDeletion& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SceneEntityDeletion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef SceneEntityDeletion_Type Type;
  static const Type MATCHING_ID =
    SceneEntityDeletion_Type_MATCHING_ID;
  static const Type ALL =
    SceneEntityDeletion_Type_ALL;
  static inline bool Type_IsValid(int value) {
    return SceneEntityDeletion_Type_IsValid(value);
  }
  static const Type Type_MIN =
    SceneEntityDeletion_Type_Type_MIN;
  static const Type Type_MAX =
    SceneEntityDeletion_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    SceneEntityDeletion_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return SceneEntityDeletion_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return SceneEntityDeletion_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return SceneEntityDeletion_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string id = 3;
  void clear_id();
  static const int kIdFieldNumber = 3;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // .google.protobuf.Timestamp timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  private:
  const ::google::protobuf::Timestamp& _internal_timestamp() const;
  public:
  const ::google::protobuf::Timestamp& timestamp() const;
  ::google::protobuf::Timestamp* release_timestamp();
  ::google::protobuf::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::google::protobuf::Timestamp* timestamp);

  // .foxglove.SceneEntityDeletion.Type type = 2;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::foxglove::SceneEntityDeletion_Type type() const;
  void set_type(::foxglove::SceneEntityDeletion_Type value);

  // @@protoc_insertion_point(class_scope:foxglove.SceneEntityDeletion)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::Timestamp* timestamp_;
  int type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_foxglove_2fSceneEntityDeletion_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SceneEntityDeletion

// .google.protobuf.Timestamp timestamp = 1;
inline bool SceneEntityDeletion::has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != NULL;
}
inline const ::google::protobuf::Timestamp& SceneEntityDeletion::_internal_timestamp() const {
  return *timestamp_;
}
inline const ::google::protobuf::Timestamp& SceneEntityDeletion::timestamp() const {
  const ::google::protobuf::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:foxglove.SceneEntityDeletion.timestamp)
  return p != NULL ? *p : *reinterpret_cast<const ::google::protobuf::Timestamp*>(
      &::google::protobuf::_Timestamp_default_instance_);
}
inline ::google::protobuf::Timestamp* SceneEntityDeletion::release_timestamp() {
  // @@protoc_insertion_point(field_release:foxglove.SceneEntityDeletion.timestamp)
  
  ::google::protobuf::Timestamp* temp = timestamp_;
  timestamp_ = NULL;
  return temp;
}
inline ::google::protobuf::Timestamp* SceneEntityDeletion::mutable_timestamp() {
  
  if (timestamp_ == NULL) {
    auto* p = CreateMaybeMessage<::google::protobuf::Timestamp>(GetArenaNoVirtual());
    timestamp_ = p;
  }
  // @@protoc_insertion_point(field_mutable:foxglove.SceneEntityDeletion.timestamp)
  return timestamp_;
}
inline void SceneEntityDeletion::set_allocated_timestamp(::google::protobuf::Timestamp* timestamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(timestamp)->GetArena();
    if (message_arena != submessage_arena) {
      timestamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:foxglove.SceneEntityDeletion.timestamp)
}

// .foxglove.SceneEntityDeletion.Type type = 2;
inline void SceneEntityDeletion::clear_type() {
  type_ = 0;
}
inline ::foxglove::SceneEntityDeletion_Type SceneEntityDeletion::type() const {
  // @@protoc_insertion_point(field_get:foxglove.SceneEntityDeletion.type)
  return static_cast< ::foxglove::SceneEntityDeletion_Type >(type_);
}
inline void SceneEntityDeletion::set_type(::foxglove::SceneEntityDeletion_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:foxglove.SceneEntityDeletion.type)
}

// string id = 3;
inline void SceneEntityDeletion::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SceneEntityDeletion::id() const {
  // @@protoc_insertion_point(field_get:foxglove.SceneEntityDeletion.id)
  return id_.GetNoArena();
}
inline void SceneEntityDeletion::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:foxglove.SceneEntityDeletion.id)
}
#if LANG_CXX11
inline void SceneEntityDeletion::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:foxglove.SceneEntityDeletion.id)
}
#endif
inline void SceneEntityDeletion::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:foxglove.SceneEntityDeletion.id)
}
inline void SceneEntityDeletion::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:foxglove.SceneEntityDeletion.id)
}
inline ::std::string* SceneEntityDeletion::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:foxglove.SceneEntityDeletion.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SceneEntityDeletion::release_id() {
  // @@protoc_insertion_point(field_release:foxglove.SceneEntityDeletion.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SceneEntityDeletion::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:foxglove.SceneEntityDeletion.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::foxglove::SceneEntityDeletion_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::foxglove::SceneEntityDeletion_Type>() {
  return ::foxglove::SceneEntityDeletion_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_foxglove_2fSceneEntityDeletion_2eproto
